#!/bin/bash
# vim:ft=sh
echo /opt/homebrew/opt/kotlin/libexec/lib/kotlin-stdlib.jar:/opt/homebrew/opt/kotlin/libexec/lib/kotlin-script-runtime.jar:/Users/sebastian.imlay/.gradle/wrapper/dists/gradle-8.4-bin/1w5dpkrfk8irigvoxmyhowfim/gradle-8.4/lib/junit-4.13.2.jar
